[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# name = "aoc2015"
path = "2015/lib.rs"

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "*"
